version: "3.2"
services:

  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   container_name: 'rabbitmq-server'
  #   ports:
  #       - 5672:5672
  #       - 15672:15672
  #   volumes:
  #       - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
  #       - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  redis:
    image: 'redis:alpine'
    container_name: 'redis-server'
    hostname: redis
    ports:
      - "6379:6379"
    expose: 
      - "6379"

  api:
    build: .
    container_name: 'api-server'
    ports:
      - "9000:9000"
    depends_on:
      - "redis"
      # - "rabbitmq"